# inflator.toml syntax documentation: https://github.com/inflated-goboscript/inflator#inflator
name = 'base'
version = "v0.0.0"
username = "inflated-goboscript"

[dependencies]
string = "string"
math = "math"
